site_name: Associazione Montessori Vallagarina
site_url: https://montessorivallagarina.it
nav:
  - Benvenuti: index.md
  - Scuola Primaria di Rovereto: scuola-rovereto.md
  - Adesione: adesione.md
  - Eventi:
    - Corso aggiornamento insegnanti: blog/2026_corso_insegnanti_matematica.md
    - Corso Litigare bene: blog/2026-02_03_litigare_bene.md
    - Novembre Dicembre 2025: blog/2025-11_12.md
    - Maggio Giugno 2025: blog/2025-05.md
    - Aprile 2025: blog/2025-04.md
    - Febbraio 2025: blog/2025-02.md
    - Gennaio 2025: blog/2025-01.md
    - Dicembre 2024: blog/2024-12.md
    - Luglio 2024: blog/2024-07.md
  - Contatta l'associazione: contatti.md
theme:
  name: material
  logo: immagini/logo.png
extra_javascript:
  - js/analytics.js
